const swissBase = {
  '--paper': '#fafaf8',
  '--paper-rgb': '250,250,248',
  '--ink': '#0a0a0a',
  '--ink-rgb': '10,10,10',
  '--grey-1': '#f0f0ee',
  '--grey-2': '#d4d4d2',
  '--grey-3': '#737373',
};

function theme(label, vars, roles = {}) {
  const palette = { ...swissBase, ...vars };
  const reportPalette = {
    '--report-red': palette['--accent'],
    '--report-red-fg': palette['--accent-on'],
    '--report-blue': palette['--accent-bright'],
    '--report-blue-fg': palette['--accent-on'],
    '--report-amber': palette['--grey-2'],
    '--report-amber-fg': palette['--ink'],
    '--report-ink': palette['--ink'],
    '--report-ink-fg': palette['--paper'],
    '--report-cream': palette['--grey-1'],
    '--report-cream-fg': palette['--ink'],
    '--report-paper': palette['--paper'],
    '--report-paper-fg': palette['--ink'],
    '--report-dot': palette['--grey-2'],
    '--report-accent-red': palette['--accent'],
    '--report-accent-blue': palette['--accent-bright'],
    '--report-accent-amber': palette['--grey-2'],
    '--report-accent-ink': palette['--ink'],
  };
  return {
    label,
    vars: {
      ...palette,
      ...reportPalette,
      '--paper-tint': palette['--grey-1'],
      '--surface-bg': palette['--paper'],
      '--surface-rgb': palette['--paper-rgb'],
      '--surface-fg': palette['--ink'],
      '--inverse-bg': palette['--ink'],
      '--inverse-rgb': palette['--ink-rgb'],
      '--inverse-fg': palette['--paper'],
      '--theme-bg-mode': 'dark',
      '--theme-bg': palette['--ink'],
      '--theme-fg': palette['--paper'],
      '--theme-backdrop': palette['--ink'],
      '--theme-panel-bg': palette['--paper'],
      '--theme-panel-fg': palette['--ink'],
      '--theme-panel-muted': palette['--grey-1'],
      '--theme-line': 'color-mix(in srgb, var(--theme-fg) 14%, transparent)',
      '--theme-decor-1': palette['--accent'],
      '--theme-decor-2': palette['--accent-bright'],
      '--theme-decor-3': palette['--grey-3'],
      '--theme-focus': palette['--accent'],
      '--theme-focus-fg': palette['--accent-on'],
      '--text-primary': palette['--ink'],
      '--text-secondary': 'color-mix(in srgb, var(--ink) 72%, var(--paper))',
      '--text-helper': palette['--grey-3'],
      '--text-placeholder': 'color-mix(in srgb, var(--ink) 38%, var(--paper))',
      '--text-on-color': palette['--accent-on'],
      '--border-subtle': palette['--grey-2'],
      '--border-strong': palette['--grey-3'],
      '--focus-bg': 'var(--theme-focus)',
      '--focus-rgb': palette['--accent-rgb'],
      '--focus-fg': 'var(--theme-focus-fg)',
      '--focus-muted': 'color-mix(in srgb, var(--focus-fg) 72%, transparent)',
      '--focus-mark': 'var(--theme-focus)',
      ...roles,
    },
  };
}

export const THEME_OPTIONS = {
  light: theme('浅色背景', {
    '--paper': '#ffffff',
    '--paper-rgb': '255,255,255',
    '--ink': '#171411',
    '--ink-rgb': '23,20,17',
    '--grey-1': '#f5f5f5',
    '--grey-2': '#d9d9d9',
    '--grey-3': '#737373',
    '--accent': '#d45b2a',
    '--accent-rgb': '212,91,42',
    '--accent-on': '#ffffff',
    '--accent-bright': '#f08a4b',
    '--ink-tint': '#29231d',
  }, {
    '--theme-bg-mode': 'light',
    '--theme-bg': '#ffffff',
    '--theme-fg': '#171411',
    '--theme-backdrop': '#ffffff',
    '--theme-panel-bg': '#171411',
    '--theme-panel-fg': '#ffffff',
    '--theme-focus': '#d45b2a',
    '--theme-decor-1': '#d45b2a',
    '--theme-decor-2': '#171411',
    '--theme-decor-3': '#d9d9d9',
    '--report-red': '#171411',
    '--report-red-fg': '#ffffff',
    '--report-blue': '#29231d',
    '--report-blue-fg': '#ffffff',
    '--report-amber': '#f2f2f2',
    '--report-amber-fg': '#171411',
    '--report-ink': '#171411',
    '--report-ink-fg': '#ffffff',
    '--report-cream': '#ffffff',
    '--report-cream-fg': '#171411',
    '--report-paper': '#ffffff',
    '--report-paper-fg': '#171411',
    '--report-dot': '#d9d9d9',
    '--report-accent-red': '#d45b2a',
    '--report-accent-blue': '#d45b2a',
    '--report-accent-amber': '#d45b2a',
    '--report-accent-ink': '#171411',
  }),
  dark: theme('深色背景', {
    '--paper': '#f4f1ea',
    '--paper-rgb': '244,241,234',
    '--ink': '#090b10',
    '--ink-rgb': '9,11,16',
    '--grey-1': '#e6e1d8',
    '--grey-2': '#cfc7ba',
    '--grey-3': '#777b83',
    '--accent': '#4e8cff',
    '--accent-rgb': '78,140,255',
    '--accent-on': '#ffffff',
    '--accent-bright': '#7cb6ff',
    '--ink-tint': '#141923',
  }, {
    '--theme-focus': '#7cb6ff',
    '--theme-decor-1': '#7cb6ff',
    '--theme-decor-2': '#f4f1ea',
    '--theme-decor-3': '#777b83',
    '--report-red': '#f4f1ea',
    '--report-red-fg': '#090b10',
    '--report-blue': '#141923',
    '--report-blue-fg': '#f4f1ea',
    '--report-amber': '#1f2632',
    '--report-amber-fg': '#f4f1ea',
    '--report-ink': '#090b10',
    '--report-ink-fg': '#f4f1ea',
    '--report-cream': '#151b25',
    '--report-cream-fg': '#f4f1ea',
    '--report-paper': '#0f131a',
    '--report-paper-fg': '#f4f1ea',
    '--report-dot': '#313a4a',
    '--report-accent-red': '#7cb6ff',
    '--report-accent-blue': '#7cb6ff',
    '--report-accent-amber': '#7cb6ff',
    '--report-accent-ink': '#f4f1ea',
  }),
  colorful: theme('多彩', {
    '--paper': '#f1ece1',
    '--paper-rgb': '241,236,225',
    '--ink': '#111317',
    '--ink-rgb': '17,19,23',
    '--grey-1': '#ebe3d4',
    '--grey-2': '#d7d3c7',
    '--grey-3': '#706b63',
    '--accent': '#e04a2f',
    '--accent-rgb': '224,74,47',
    '--accent-on': '#ffffff',
    '--accent-bright': '#2c4bd0',
    '--ink-tint': '#24262b',
  }, {
    '--theme-bg-mode': 'light',
    '--theme-bg': '#f1ece1',
    '--theme-fg': '#111317',
    '--theme-backdrop': '#f1ece1',
    '--theme-panel-bg': '#fffaf0',
    '--theme-panel-fg': '#111317',
    '--theme-focus': '#e04a2f',
    '--theme-decor-1': '#e04a2f',
    '--theme-decor-2': '#2c4bd0',
    '--theme-decor-3': '#f4b73e',
    '--report-red': '#e04a2f',
    '--report-red-fg': '#ffffff',
    '--report-blue': '#2c4bd0',
    '--report-blue-fg': '#ffffff',
    '--report-amber': '#f4b73e',
    '--report-amber-fg': '#111317',
    '--report-ink': '#111317',
    '--report-ink-fg': '#ffffff',
    '--report-cream': '#f1ece1',
    '--report-cream-fg': '#111317',
    '--report-paper': '#ffffff',
    '--report-paper-fg': '#111317',
    '--report-dot': '#d7d3c7',
    '--report-accent-red': '#e04a2f',
    '--report-accent-blue': '#2c4bd0',
    '--report-accent-amber': '#f4b73e',
    '--report-accent-ink': '#111317',
    '--bt-page-bg': '#f1ece1',
    '--bt-page-fg': '#111317',
    '--bt-panel-bg': '#fffaf0',
    '--bt-panel-fg': '#111317',
    '--bt-card-bg': '#ffffff',
    '--bt-card-fg': '#111317',
    '--bt-card-alt-bg': '#f4b73e',
    '--bt-card-alt-fg': '#111317',
    '--bt-color-red': '#e04a2f',
    '--bt-color-blue': '#2c4bd0',
    '--bt-color-amber': '#f4b73e',
    '--bt-color-cream': '#f1ece1',
    '--bt-color-ink': '#111317',
  }),
};

export const DEFAULT_THEME = 'dark';
