export const TYPE_SCALE_OPTIONS = {
  large: {
    label: '大字号',
    vars: {
      '--fs-display': '10vw',
      '--fs-h1': '7.6vw',
      '--fs-h2': '5.6vw',
      '--fs-h3': '4.6vw',
      '--fs-h4': '2.5vw',
      '--fs-subtitle': '2.1vw',
      '--fs-lead': '1.55vw',
      '--fs-body': 'max(18px,1.08vw)',
      '--fs-body-sm': 'max(16px,.92vw)',
      '--fs-caption': '14px',
      '--fs-number-lg': '13vw',
      '--fs-number-md': '5.4vw',
    },
  },
  medium: {
    label: '中字号',
    vars: {
      '--fs-display': '8.8vw',
      '--fs-h1': '6.6vw',
      '--fs-h2': '4.8vw',
      '--fs-h3': '4vw',
      '--fs-h4': '2.2vw',
      '--fs-subtitle': '1.85vw',
      '--fs-lead': '1.36vw',
      '--fs-body': 'max(17px,1vw)',
      '--fs-body-sm': 'max(15px,.86vw)',
      '--fs-caption': '13px',
      '--fs-number-lg': '11vw',
      '--fs-number-md': '4.8vw',
    },
  },
  small: {
    label: '小字号',
    vars: {
      '--fs-display': '7.2vw',
      '--fs-h1': '5.4vw',
      '--fs-h2': '4vw',
      '--fs-h3': '3.3vw',
      '--fs-h4': '1.8vw',
      '--fs-subtitle': '1.5vw',
      '--fs-lead': '1.14vw',
      '--fs-body': 'max(16px,.9vw)',
      '--fs-body-sm': 'max(14px,.78vw)',
      '--fs-caption': '12px',
      '--fs-number-lg': '9vw',
      '--fs-number-md': '4vw',
    },
  },
};

export const DEFAULT_TYPE_SCALE = 'medium';
